/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeFunction_NativeLib */

#ifndef _Included_nativeFunction_NativeLib
#define _Included_nativeFunction_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeFunction_NativeLib
 * Method:    OSGRun
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeFunction_NativeLib_OSGRun
  (JNIEnv *, jclass);

/*
 * Class:     nativeFunction_NativeLib
 * Method:    initOSG
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_nativeFunction_NativeLib_initOSG
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
